// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kolokwium_pk.Models;

namespace kolokwium_pk.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20200704151913_firefighters2")]
    partial class firefighters2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kolokwium_pk.Models.Action", b =>
                {
                    b.Property<int>("IdAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NeedSpecialEquipment")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAction");

                    b.ToTable("Actions");

                    b.HasData(
                        new
                        {
                            IdAction = 3,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NeedSpecialEquipment = false,
                            StartTime = new DateTime(2020, 7, 4, 17, 19, 12, 935, DateTimeKind.Local).AddTicks(483)
                        },
                        new
                        {
                            IdAction = 4,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NeedSpecialEquipment = false,
                            StartTime = new DateTime(2020, 7, 4, 17, 19, 12, 941, DateTimeKind.Local).AddTicks(6698)
                        },
                        new
                        {
                            IdAction = 5,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NeedSpecialEquipment = true,
                            StartTime = new DateTime(2020, 7, 4, 17, 19, 12, 941, DateTimeKind.Local).AddTicks(6807)
                        });
                });

            modelBuilder.Entity("kolokwium_pk.Models.Firefighter", b =>
                {
                    b.Property<int>("IdFirefighter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFirefighter");

                    b.ToTable("Firefighters");

                    b.HasData(
                        new
                        {
                            IdFirefighter = 1,
                            FirstName = "Piotr",
                            LastName = "Kwiatek"
                        });
                });

            modelBuilder.Entity("kolokwium_pk.Models.FirefighterAction", b =>
                {
                    b.Property<int>("IdFirefighter")
                        .HasColumnType("int");

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.HasKey("IdFirefighter", "IdAction");

                    b.ToTable("FirefighterActions");

                    b.HasData(
                        new
                        {
                            IdFirefighter = 1,
                            IdAction = 3
                        },
                        new
                        {
                            IdFirefighter = 1,
                            IdAction = 4
                        },
                        new
                        {
                            IdFirefighter = 1,
                            IdAction = 5
                        });
                });

            modelBuilder.Entity("kolokwium_pk.Models.Firetruck", b =>
                {
                    b.Property<int>("IdFiretruck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OperationalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<bool>("SpecialEquipment")
                        .HasColumnType("bit");

                    b.HasKey("IdFiretruck");

                    b.ToTable("Firetrucks");

                    b.HasData(
                        new
                        {
                            IdFiretruck = 1,
                            OperationalNumber = "ABC1111",
                            SpecialEquipment = true
                        },
                        new
                        {
                            IdFiretruck = 2,
                            OperationalNumber = "XXX1111",
                            SpecialEquipment = false
                        });
                });

            modelBuilder.Entity("kolokwium_pk.Models.FiretruckAction", b =>
                {
                    b.Property<int>("IdFiretruck")
                        .HasColumnType("int");

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFiretruckAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("IdFiretruck", "IdAction");

                    b.ToTable("FiretruckActions");
                });
#pragma warning restore 612, 618
        }
    }
}
